name: iit414w-lab01
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - notebook
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - requests
  - scikit-learn
  - pip
  - pip:
      - jupyterlab
